### ISSUE TITLE
Invalid Document error

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [GovTechSG/certificate-application#139]
Hi, we're signing around 4k+ files using the CLI tool, we got a "Invalid Document" failure on just the 2 of them, but it doesn't pinpoint on which specific part of the file is the error. It's just weird that 4k of them are all in the same batch same format/layout only 2 failed. Is there any way to spot the cause of the issue?

**Comment by Nebulis** [comment]
I don't see why it's weird 😉.

Iirc correctly this cli display the content of the file that errored out so if you have the file and the schema you can try to find the problem here: https://www.jsonschemavalidator.net

If you can I also recommend you to use open attestation cli https://docs.opencerts.io/docs/transcripts

We support displaying some kind of error (can support more if needed) and the full path of the file

**Comment by SP-INDT-OpenCert** [comment]
No issue/error in the JSon validator which is the 1st thing I did yesterday. I checked the output of the CLI it didn't specify where the specific error is. It just show:
"2020-03-25T07:05:58.609Z error: Invalid document:{ <then proceed to display the file content>"

The weird thing for me, is that these batch of files are all using the same template & formatting, so if there will be a format issue then all of them will hit the problems not just the 2 files. I'm trying to eye check the data and also if there are any special characters, everything seems to be normal.

**Comment by Nebulis** [comment]
Certificate?

**Comment by SP-INDT-OpenCert** [comment]
yes they are open certs files. 
2019 certs - no issue
2018 certs - failed on 2 certs

**Comment by Nebulis** [comment]
No, Share a cert with problem otherwise i can't help you

**Comment by SP-INDT-OpenCert** [comment]
Please see attached masked file:

[Invalid Document.zip](https://github.com/OpenCerts/certificate-cli/files/4385079/Invalid.Document.zip)

**Comment by Nebulis** [comment]
I tried your document on https://www.jsonschemavalidator.net/

![image](https://user-images.githubusercontent.com/503185/77615180-a47b1380-6f69-11ea-9fd8-3b462ee620b2.png)

And indeed both contain invalid date, once the date is fixed the problem disappear.

Some recommendation:
- Use documentStore instead of certificateStore (certificateStore shouldn't have existed for schema v2)
- As you use `identityProof`, I strongly encourage you to move to open-attestation-cli and follow the instruction in the link above. The CLI display some kind of error. I think this one wouldn't be displayed correctly for the moment. If you dare using the tool and opening an issue, I could check and improve the output for this kind of error

**Comment by SP-INDT-OpenCert** [comment]
Thanks!! I'll check this open-attestation.
Just quick question on the open-attestation, this is only for wrapping of the opencert file, and the new flow will be like:
Generate JSon file --> Wrapped via open-attestation-cli --> Signed via certificate-cli

instead of earlier approach of:
Generate JSon file --> Signed via certificate-cli

**Comment by Nebulis** [comment]
The process will remain the same:

```
Generate JSon file --> Wrapped via open-attestation-cli
```
vs
```
Generate JSon file --> Signed via certificate-cli
```

Wrapped and signed are doing the same thing. We renamed signing to wrapping because **we are not signing** certificate, and the terminology is misleading.

**Comment by SP-INDT-OpenCert** [comment]
Thanks for the confirmation, current process still working right?
Because our staffs are generating for 5yrs worth of files now, and we may not have enough time to implement the new changes.

**Comment by Nebulis** [comment]
Yes no worries on that, if any problem it's a bug and I will fix it
